#ifndef __TIMEX_EVENTS
#define __TIMEX_EVENTS

// Nicer names for some button events.
#define COREEVENT_MODEDEPRESS COREEVENT_SWITCH1DEPRESS
#define COREEVENT_STOPRESETDEPRESS COREEVENT_SWITCH2DEPRESS
#define COREEVENT_STARTSPLITDEPRESS COREEVENT_SWITCH3DEPRESS
#define COREEVENT_MODERELEASE COREEVENT_SWITCH1RELEASE
#define COREEVENT_STOPRESETRELEASE COREEVENT_SWITCH2RELEASE
#define COREEVENT_STARTSPLITRELEASE COREEVENT_SWITCH3RELEASE

enum APPLICATION_SYSTEM_EVENTS {
    COREEVENT_CROWN_EL_DEPRESS      = 0x00,
    COREEVENT_CROWN_HOME            = 0x01,
    COREEVENT_CROWN_SET1            = 0x02,
    COREEVENT_CROWN_SET             = 0x02,
    COREEVENT_CROWN_SET2            = 0x03,
    COREEVENT_CW_EDGE_LEADING       = 0x04,
    COREEVENT_CCW_EDGE_LEADING      = 0x05,
    COREEVENT_SWITCH1DEPRESS        = 0x06,
    COREEVENT_SWITCH2DEPRESS        = 0x07,
    COREEVENT_SWITCH3DEPRESS        = 0x08,
    COREEVENT_MELODYPOPUPCANCEL     = 0x0F,
    COREEVENT_CROWN_EL_RELEASE      = 0x80,
    COREEVENT_CW_EDGE_TRAILING      = 0x84,
    COREEVENT_CCW_EDGE_TRAILING     = 0x85,
    COREEVENT_SWITCH1RELEASE        = 0x86,
    COREEVENT_SWITCH2RELEASE        = 0x87,
    COREEVENT_SWITCH3RELEASE        = 0x88,
    COREEVENT_CW_PULSES             = 0x10,
    COREEVENT_CCW_PULSES            = 0x11,
    COREEVENT_ANYSWITCHDEPRESS      = 0x12,
    COREEVENT_ANYSWITCHRELEASE      = 0x13,
    COREEVENT_TIMEOUTDONE_LOWRES    = 0x20,
    COREEVENT_TIMEOUTDONE_HIGHRES   = 0x21,
    COREEVENT_STICKY_TIMEOUTDONE    = 0x22,
    COREEVENT_STATEENTRY            = 0x31,
    COREEVENT_MELODY_DONE           = 0x32,
    COREEVENT_END_OF_SCROLLING_MESS = 0x33,
    COREEVENT_EVENTGENERATION       = 0x34,
    COREEVENT_ICON_REFRESH          = 0x35,
    COREEVENT_DISPLAY_UPDATE_TODRES = 0x40,
    COREEVENT_DISPLAY_UPDATE_STPRES = 0x41,
    COREEVENT_DISPLAY_UPDATE_TMRRES = 0x42,
    COREEVENT_DISPLAY_UPDATE_SYNRES = 0x43,
    COREEVENT_COMMDATAPACKETREADY   = 0x50,
    COREEVENT_COMMFIRSTBYTERECEIVED = 0x51,
    COREEVENT_COMMDISCONNECTED      = 0x52,
    COREEVENT_COMMTRANSMITCOMPLETE  = 0x53
};

#define COREEVENT_APP_SHUTDOWN_FOR_COMM COREEVENT_UPDATEDATABASEHEADER

enum BACKGROUND_HANDLER_EVENTS {
    COREEVENT_NULL                  = 0x00,
    COREEVENT_PORINIT               = 0x01,
    COREEVENT_INIT                  = 0x02,
    COREEVENT_TASKEXIT              = 0x03,
    COREEVENT_PEEK                  = 0x04,
    COREEVENT_UPDATEDATABASEHEADER  = 0x05,
    COREEVENT_TIMERFINISHED         = 0x06,
    COREEVENT_TIMERHALFWAYACHIEVED  = 0x07,
    COREEVENT_STP_FORCIBLY_STARTED  = 0x08,
    COREEVENT_STP_RUNOUT            = 0x09,
    COREEVENT_TZC_EXPIRED_NOPOPUP   = 0x0A,
    COREEVENT_TZC_EXPIRED_POPUP     = 0x0B,
    COREEVENT_PRIMARY_TIME_CHANGE   = 0x82,
    COREEVENT_REFRESH_START         = 0x81,
    COREEVENT_REFRESH_CONTINUE      = 0x80,
    COREEVENT_PEEK_SEARCH_START     = 0x41,
    COREEVENT_PEEK_SEARCH_CONTINUE  = 0x40,
    COREEVENT_DAY_UPDATE            = 0x21,
    COREEVENT_DAY_UPDATE_START      = 0x21,
    COREEVENT_DAY_UPDATE_CONTINUE   = 0x20,
    COREEVENT_HOUR_UPDATE           = 0x11,
    COREEVENT_HOUR_UPDATE_START     = 0x11,
    COREEVENT_HOUR_UPDATE_CONTINUE  = 0x10
};

// If you declare an _sfrbyte, the compiler understands it will be volatile.
_sfrbyte CORECurrentEvent _at(0xF102);
_sfrbyte COREBackgroundEvent _at(0xF10A);

#endif
